name: Keep Alive
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:        # 👈 add this line
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl https://e-commerce-d2dn.onrender.com/api/products/
